# Generated by Django 4.1.13 on 2024-12-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherConditions",
            fields=[
                ("condition_id", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(auto_now=True)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                ("additional_info", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name="weatherconditions",
            constraint=models.CheckConstraint(
                check=models.Q(("time__isnull", False)), name="time_is_not_null"
            ),
        ),
        migrations.AddConstraint(
            model_name="weatherconditions",
            constraint=models.CheckConstraint(
                check=models.Q(("temperature__gt", -55)), name="temperature_gt_-55"
            ),
        ),
        migrations.AddConstraint(
            model_name="weatherconditions",
            constraint=models.CheckConstraint(
                check=models.Q(("temperature__lt", 125)), name="temperature_lt_125"
            ),
        ),
    ]
