# Generated by Django 4.1.13 on 2024-12-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weatherApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherconditions",
            name="additional_info",
            field=models.CharField(default="", max_length=100),
        ),
    ]
