name: CI
on: 
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
      branches:
      - main

jobs:
  setup-python:
    name: Set up Python environment
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==1.8.5

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.3'
          cache: 'poetry'

      - name: Install packages
        run: poetry install

      - name: Set up proper env variables
        run: echo "W1THERMSENSOR_NO_KERNEL_MODULE=1" >> $GITHUB_ENV

      - name: Run tests
        working-directory: ./CommandCenter
        run: poetry run coverage run manage.py test --settings=CommandCenter.test_settings --exclude-tag=only_local

      - name: Test coverage report view and generate html test coverage report
        working-directory:
        run: | 
          poetry run coverage report --fail-under=70 --data-file=./CommandCenter/.coverage
          poetry run coverage html --data-file=./CommandCenter/.coverage
          poetry run coverage xml --data-file=./CommandCenter/.coverage

      - name: Upload test coverage report summary
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: ./htmlcov/

      - name: Publish coverage results for PR
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: ./coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}


  black-format:
    name: Black formatting
    needs: setup-python
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Black formatting
        uses: reviewdog/action-black@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check.
          level: warning
          verbose: true
      
