name: CI
on: 
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
      branches:
      - main

jobs:
  setup-python:
    name: Set up Python environment
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.3'
          cache: 'poetry'

      - name: Install packages
        run: poetry install
  
      - rame: Run tests
        run: poetry run coverage run CommandCenter/manage.py test

      - name: Test coverage report view
        run: poetry run coverage report
      
      - name: Generate html test coverage report
        run: poetry run coverage html

      - name: Upload test coverage report summary
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: htmlcov/

      
      
  # black-format:
  #   name: Black formatting
  #   needs: setup-python
  #   runs-on: ubuntu-latest
  #   continue-on-error: true
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v4

  #     - name: Black formatting
  #       uses: reviewdog/action-black@v3
  #       with:
  #         github_token: ${{ secrets.github_token }}
  #         reporter: github-pr-check.
  #         level: warning
  #         verbose: true
      